### ISSUE TITLE
Loosen bounds on base

### ISSUE THREAD

**Issue by vmchale** [bos/vector-binary-instances#21]
This works with GHC 9.0.1

**Comment by RyanGlScott** [comment]
The library component of `vector-binary-instances` compiles with GHC 9.0.1, at least. The benchmarks, unfortunately, do not yet compile with 9.0.1 due to `gauge`'s dependency on `basement`—see haskell-foundation/foundation#548.

**Comment by Bodigrim** [comment]
One can replace `gauge` with `tasty-bench`, the latter has no issues with GHC 9.0.
