### ISSUE TITLE
Allow vector-0.13

### ISSUE THREAD

**Issue by andreasabel** [bos/vector-binary-instances#24]
Blocking: 
- https://github.com/haskellari/binary-instances/issues/20
- https://github.com/haskell-github/github/issues/485
- https://github.com/commercialhaskell/stackage/issues/6624

Ping @bgamari.

**Comment by andreasabel** [comment]
I hope this will be done by the `vector` folks, see
- https://github.com/haskell/vector/issues/442

**Comment by bgamari** [comment]
I have pushed [revision 2](https://hackage.haskell.org/package/vector-binary-instances-0.2.5.2) which bumps the `vector` upper bound.
