### ISSUE TITLE
Loosen base bounds for GHC 9.6 support.

### ISSUE THREAD

**Issue by athas** [bos/vector-binary-instances#27]
The bounds for `base` are too restrictive.  The code works fine on GHC 9.6, though.  A release is not necessary, but a Hackage revision would be appreciated.

**Comment by juhp** [comment]
@hackage-trustees is it possible to have a revision?

**Comment by andreasabel** [comment]
@juhp  Thanks for the notification.  
I didn't receive anything; is there a way in GitHub to subscribe to organization notifications like @hackage-trustees ?
Otherwise, filing to https://github.com/haskell-infra/hackage-trustees would get my attention.

**Comment by andreasabel** [comment]
Done: https://hackage.haskell.org/package/vector-binary-instances-0.2.5.2/revisions/

**Comment by juhp** [comment]
Thanks - sorry I dunno, I was just assuming/hoping...

_edit_ ah it is @hackage-trustees hmm then I don't know. There is Follow for orgs, but dunno if that triggers notifications, probably not? Hm
